name: linux-gcc-x64
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  cloud-ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install-tools
      run: |
        uname --all
        sudo apt-get update
        sudo apt-get install cmake ninja-build gcc-11 g++-11 qtbase5-dev qt5-qmake qttools5-dev qttools5-dev-tools libgl1-mesa-dev libboost-all-dev bison flex
    - name: build
      env:
        CC: gcc-11
        CXX: g++-11
        TYPE: Release
      run: |
        $CC --version
        $CXX --version
        mkdir build && cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=${TYPE} ..
        cmake --build .
    - name: test
      run: cd build && ctest
